### ISSUE TITLE
[0.7.x only] The type name 'OperationAbortedException' could not be found in the namespace 'System.Data'.

### ISSUE THREAD

**Issue by elafarge** [opentracing-contrib/csharp-netcore#87]
Hello, and thanks a lot for all the work introduced in this lib.

I think I've spotted a bug when bumping to 0.7.1. I can't import the OperationAbortedException any more and have the following error:

```
error CS1069: The type name 'OperationAbortedException' could not be found in the namespace 'System.Data'. This type has been forwarded to assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=REDACTED' Consider adding a reference to that assembly.
```

Rolling back to 0.6.2 fixes the issue however.

I'd love to contribute but I'm a bit lost on where to start. Some pointers would be highly appreciated :) 

Many thanks in advance,

Regards,

-Étienne
